---
# Install and configure WireGuard

- name: Install WireGuard
  package:
    name: wireguard-tools
    state: present

- name: Ensure /etc/wireguard exists
  file:
    path: /etc/wireguard
    state: directory
    mode: 0700

- name: Deploy wg0.conf
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: 0600

- name: Enable and start wg-quick@wg0
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started
